# Generated by Django 4.0.3 on 2022-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_posts_user'),
        ('accounts', '0004_alter_profile_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='profile_like', to='webapp.posts'),
        ),
    ]
