# Generated by Django 4.0.3 on 2022-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
