# Generated by Django 4.0.3 on 2022-04-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
